# initfile for eavesdrop PGSQL event listener

globals:
    database_host: 52.202.20.45
    database_name: testbed
    debug: True
    handler_module: sample_handlers
    project_dir: $MERCURY_HOME
    service_module: mx_services
    


service_objects:
       

channels:
        ch_instructor_insert:
                db_operation: INSERT
                db_table_name: instructors
                db_proc_name: instructors_update_notify
                db_trigger_name: trg_instructors_insert         
                handler_function: handle_instructors_insert
                payload_fields:
                        - id
                        - first_name
                        - last_name
                        - email
                        - userid
                        - deleted
                        - expired
                        - prev_id



